name: Build Rust for macOS x86_64

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: sc-core

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            sc-core/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('sc-core/**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build release
        env:
          SQLX_OFFLINE: true
        run: cargo build --release --target x86_64-apple-darwin

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-macos-x86_64
          path: sc-core/target/x86_64-apple-darwin/release/
          retention-days: 30
